_BASE_: "Base-DiffusionDet_seaclear.yaml"
MODEL:
  WEIGHTS: "/home/rbu/Comparison_Paper_Object_Detection/DiffusionDet/pretrained_model/diffdet_coco_swinbase.pth"
  BACKBONE:
    NAME: build_swintransformer_fpn_backbone
  SWIN:
    SIZE: B-22k
  FPN:
    IN_FEATURES: ["swin0", "swin1", "swin2", "swin3" ]
  DiffusionDet:
    NUM_PROPOSALS: 500
    NUM_CLASSES: 40 # Seaclear
DATASETS:
  TRAIN: ("seaclear_train",)
  TEST:  ("seaclear_val",)
SOLVER:
  STEPS: (350000, 420000)
  MAX_ITER: 450000
INPUT:
  CROP:
    ENABLED: True
  FORMAT: "RGB"
